### ISSUE TITLE
Experiment launcher

### ISSUE THREAD

**Issue by AasherH** [joaoamcarvalho/mpd-public#1]
I get an error "deps/experiment_launcher does not appear to be a Python project: neither setup.py nor pyproject.toml found." Has anyone else gotten this error?

**Comment by changchencc** [comment]
Same here. The same error also happens to  torch_robotics, motion_planning_baselines, and storm installing. I think this may caused by those empty folders under /deps. The author might forget to upload some files.

**Comment by jacarvalho** [comment]
I'm sorry that you are experiencing some issues.

Can you clone the repo again and fetch the submodules with:

```bash
git clone git@github.com:jacarvalho/mpd-public.git
cd mpd-public
git submodule update --init --recursive --progress
```

Can you now see the files under the `deps` folder?

**Comment by joaoamcarvalho** [comment]
Sorry that you experienced some issues with the installation.
There was an issue with pulling the submodules in `deps`, but it should be fixed now.
Please pull the latest repo and let me now if it worked.

**Comment by changchencc** [comment]
Hi @jacarvalho, Thanks for your quick response! I still have the same error. Seems something wrong with the git permission.

> Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/experiment_launcher'...             
> remote: Enumerating objects: 899, done.                                                                            
> remote: Counting objects: 100% (744/744), done.                                                                    
> remote: Compressing objects: 100% (335/335), done.                                                                 
> remote: Total 899 (delta 431), reused 697 (delta 404), pack-reused 155                                             
> Receiving objects: 100% (899/899), 114.06 KiB | 581.00 KiB/s, done.                                                
> Resolving deltas: 100% (502/502), done.                                                                            
> Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines'...       
> git@github.com: Permission denied (publickey).                                                                     
> fatal: Could not read from remote repository.                                                                      
>                                                                                                                    
> Please make sure you have the correct access rights                                                                
> and the repository exists.                                                                                         
> fatal: clone of 'git@github.com:anindex/motion_planning_baselines.git' into submodule path '/common/home/cc1547/pro
> jects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines' failed                                        
> Failed to clone 'deps/motion_planning_baselines'. Retry scheduled                                                  
> Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/storm'...                           
> git@github.com: Permission denied (publickey).                                                                     
> fatal: Could not read from remote repository.                                                                      
>                                                                                                                    
> Please make sure you have the correct access rights                                                                
> and the repository exists.                                                                                         
> fatal: clone of 'git@github.com:jacarvalho/storm.git' into submodule path '/common/home/cc1547/projects/dreamDiff/d
> iffusers/mpd-public/deps/storm' failed                                                                             
> Failed to clone 'deps/storm'. Retry scheduled                                                                      
> Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/torch_robotics'...                  
> git@github.com: Permission denied (publickey).                                                                     
> fatal: Could not read from remote repository.                                                                      
>                                                                                                                    
> Please make sure you have the correct access rights                                                                
> and the repository exists.                                                                                         
> fatal: clone of 'git@github.com:anindex/torch_robotics.git' into submodule path '/common/home/cc1547/projects/dream
> Diff/diffusers/mpd-public/deps/torch_robotics' failed                                                              
> Failed to clone 'deps/torch_robotics'. Retry scheduled                                                             
> Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines'...       
> git@github.com: Permission denied (publickey).                                                                     
> fatal: Could not read from remote repository.

**Comment by AasherH** [comment]
> Hi @jacarvalho, Thanks for your quick response! I still have the same error. Seems something wrong with the git permission.
> 
> > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/experiment_launcher'...
> > remote: Enumerating objects: 899, done.
> > remote: Counting objects: 100% (744/744), done.
> > remote: Compressing objects: 100% (335/335), done.
> > remote: Total 899 (delta 431), reused 697 (delta 404), pack-reused 155
> > Receiving objects: 100% (899/899), 114.06 KiB | 581.00 KiB/s, done.
> > Resolving deltas: 100% (502/502), done.
> > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines'...
> > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > fatal: Could not read from remote repository.
> > Please make sure you have the correct access rights
> > and the repository exists.
> > fatal: clone of '[git@github.com](mailto:git@github.com):anindex/motion_planning_baselines.git' into submodule path '/common/home/cc1547/pro
> > jects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines' failed
> > Failed to clone 'deps/motion_planning_baselines'. Retry scheduled
> > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/storm'...
> > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > fatal: Could not read from remote repository.
> > Please make sure you have the correct access rights
> > and the repository exists.
> > fatal: clone of '[git@github.com](mailto:git@github.com):jacarvalho/storm.git' into submodule path '/common/home/cc1547/projects/dreamDiff/d
> > iffusers/mpd-public/deps/storm' failed
> > Failed to clone 'deps/storm'. Retry scheduled
> > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/torch_robotics'...
> > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > fatal: Could not read from remote repository.
> > Please make sure you have the correct access rights
> > and the repository exists.
> > fatal: clone of '[git@github.com](mailto:git@github.com):anindex/torch_robotics.git' into submodule path '/common/home/cc1547/projects/dream
> > Diff/diffusers/mpd-public/deps/torch_robotics' failed
> > Failed to clone 'deps/torch_robotics'. Retry scheduled
> > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines'...
> > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > fatal: Could not read from remote repository.

it looks like you don't have a ssh key set up with you GitHub account. This reference should help https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by AasherH** [comment]
After installing the new repo, my environment is unable to locate all repos in the /deps folder. Does anyone have a clean way to specify the correct path such that I have access to these? I have been trying to set paths manually but began running into other errors

**Comment by changchencc** [comment]
> > Hi @jacarvalho, Thanks for your quick response! I still have the same error. Seems something wrong with the git permission.
> > > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/experiment_launcher'...
> > > remote: Enumerating objects: 899, done.
> > > remote: Counting objects: 100% (744/744), done.
> > > remote: Compressing objects: 100% (335/335), done.
> > > remote: Total 899 (delta 431), reused 697 (delta 404), pack-reused 155
> > > Receiving objects: 100% (899/899), 114.06 KiB | 581.00 KiB/s, done.
> > > Resolving deltas: 100% (502/502), done.
> > > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines'...
> > > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > > fatal: Could not read from remote repository.
> > > Please make sure you have the correct access rights
> > > and the repository exists.
> > > fatal: clone of '[git@github.com](mailto:git@github.com):anindex/motion_planning_baselines.git' into submodule path '/common/home/cc1547/pro
> > > jects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines' failed
> > > Failed to clone 'deps/motion_planning_baselines'. Retry scheduled
> > > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/storm'...
> > > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > > fatal: Could not read from remote repository.
> > > Please make sure you have the correct access rights
> > > and the repository exists.
> > > fatal: clone of '[git@github.com](mailto:git@github.com):jacarvalho/storm.git' into submodule path '/common/home/cc1547/projects/dreamDiff/d
> > > iffusers/mpd-public/deps/storm' failed
> > > Failed to clone 'deps/storm'. Retry scheduled
> > > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/torch_robotics'...
> > > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > > fatal: Could not read from remote repository.
> > > Please make sure you have the correct access rights
> > > and the repository exists.
> > > fatal: clone of '[git@github.com](mailto:git@github.com):anindex/torch_robotics.git' into submodule path '/common/home/cc1547/projects/dream
> > > Diff/diffusers/mpd-public/deps/torch_robotics' failed
> > > Failed to clone 'deps/torch_robotics'. Retry scheduled
> > > Cloning into '/common/home/cc1547/projects/dreamDiff/diffusers/mpd-public/deps/motion_planning_baselines'...
> > > [git@github.com](mailto:git@github.com): Permission denied (publickey).
> > > fatal: Could not read from remote repository.
> 
> it looks like you don't have a ssh key set up with you GitHub account. This reference should help https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

oh, thank you! I will try that later. I manually cloned those repos in the folders. It seems to work.

**Comment by joaoamcarvalho** [comment]
@AasherH @changchencc I've updated the installation instructions and tested them in a fresh virtual machine. Let me know if you still have issued with the installation.

**Comment by liuhuidong-nxu** [comment]
Can't find the experiment_launcher file?

**Comment by hhhdbbs** [comment]
> Can't find the experiment_launcher file?

I'm having the same problem, is there a solution？

**Comment by Houzezhen** [comment]
> > Can't find the experiment_launcher file?
> 
> I'm having the same problem, is there a solution？

I encountered the same problem, have you solved it yet

**Comment by hhhdbbs** [comment]
> > > Can't find the experiment_launcher file?
> > 
> > 
> > I'm having the same problem, is there a solution？
> 
> I encountered the same problem, have you solved it yet

https://github.com/yoraish/mmd/tree/7b28cb2f04b1c66a774217a52b5affa752d42a8c/deps/experiment_launcher

**Comment by hhhdbbs** [comment]
i found this
